"""unique url

Revision ID: b7e812377d99
Revises: a7fe384fbe5c
Create Date: 2026-09-25 16:50:53.302839

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b7e812377d99'
down_revision: str | Sequence[str] | None = 'a7fe384fbe5c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Keep the oldest link for each URL so the unique index can be created.
    op.execute("DELETE FROM links WHERE id NOT IN (SELECT MIN(id) FROM links GROUP BY url)")
    op.create_index(op.f('ix_links_url'), 'links', ['url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_links_url'), table_name='links')
    # ### end Alembic commands ###
